function [fitresult, gof] = fitMaxwell_1arm(freq_axis_rad_cut, finessed_Q_cut_r,lnr)
%CREATEFIT(FREQ_AXIS_RAD_CUT,FINESSED_Q_CUT_R)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : freq_axis_rad_cut
%      Y Output: finessed_Q_cut_r
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Oct-2021 17:12:51

% I used MATLAB CFTOOL to create the fitting code

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( freq_axis_rad_cut, finessed_Q_cut_r );

% Set up fittype and options.
fit_str = ...
    sprintf('abs(AA + G1 - G1/(1+tau * (1-exp(-%.4f)*exp(-1i*x))))',lnr);
ft = fittype( fit_str, 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );


opts.StartPoint = [10000 10000 1];
opts.MaxFunEvals = 6000;
opts.Display = 'Off';
opts.MaxIter = 40000;
opts.StartPoint = [0.957506835434298 0.964888535199277 0.157613081677548];
opts.TolFun = 1e-10;
opts.TolX = 1e-10;
opts.Lower = [0 0 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

end

